version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Shanghai"
    labels:
      - "dependencies"
    assignees:
      - "Timer-u"
    groups:
      production-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(dev-deps)"
    versioning-strategy: increase
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Shanghai"
    labels:
      - "dependencies"
    assignees:
      - "Timer-u"
    commit-message:
      prefix: "chore(actions)"
